name: Lint-bash

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checking commit"
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: |
          chmod +x scripts/lint.bash
          ls -l  scripts/lint.bash
          scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.23
        with:
          args: -color
