[book]
title = "<PROJECT NAME>>"
description = "<PROJECT NAME> Homepage>"
src = "."

[output.html]
git-repository-url = "<TOOL REPO>/"
edit-url-template = "<TOOL REPO>/edit/<PRIMARY BRANCH>/{path}"
additional-css = ["./docs/theme/custom.css"]
theme = "./docs/theme"
